In [54]:
import copy

TEST_MATRIX_SIZE = 12
import numpy as np

# Generate a small test set
Test_Adjacency_Matrix = np.random.randint(20, size=(TEST_MATRIX_SIZE,TEST_MATRIX_SIZE))
Test_Adjacency_Matrix = np.add(Test_Adjacency_Matrix, np.ones(TEST_MATRIX_SIZE, dtype=int))

for i in range(len(Test_Adjacency_Matrix[0])):
    for j in range(i , len(Test_Adjacency_Matrix[1])):
        if i==j:
            Test_Adjacency_Matrix[i][j] = 0
        else:
            Test_Adjacency_Matrix[i,j] = Test_Adjacency_Matrix[j,i]

print(Test_Adjacency_Matrix)

Target_Data = Test_Adjacency_Matrix

[[ 0 20 17 17 14 12 15 18 15  2 10  7]
 [20  0 12  7  5 14 15  3 17  1  3 14]
 [17 12  0  7 16 16  8  9 17  7  6  6]
 [17  7  7  0 19  1  4  5  2  7 16  1]
 [14  5 16 19  0 14  8  5 19  3 12  5]
 [12 14 16  1 14  0 14  2 13 12  5  5]
 [15 15  8  4  8 14  0 12 10 16  8  7]
 [18  3  9  5  5  2 12  0 15  7  5  8]
 [15 17 17  2 19 13 10 15  0 19  7 10]
 [ 2  1  7  7  3 12 16  7 19  0 16 12]
 [10  3  6 16 12  5  8  5  7 16  0  6]
 [ 7 14  6  1  5  5  7  8 10 12  6  0]]


In [55]:
import copy
def Minimum_Travel_Distance_by_DP(given_array, h, s):
    if(s > h+1):
        # print(f'computing min({h}, {s})')
        travel_distance_wo_swap = Get_Schedule_Length(given_array)
        min = travel_distance_wo_swap

        for u in range(h+2, s):
            array = given_array
            # print(f'array before swap: {array}')
            # swap
            array[u], array[h+1] = array[h+1], array[u]
            # print(f'swap array[{h+1}] & array[{u}], array after swap: {array}')
            travel_distance_of_first_part = Minimum_Travel_Distance_by_DP(array, h, h+1)
            travel_distance_of_second_part = Minimum_Travel_Distance_by_DP(array, h+1, s)
            travel_distance_after_swap = travel_distance_of_first_part + travel_distance_of_second_part
            # array = np.concatenate((array_of_first_part, array_of_second_part))
            # print(f'after swapping array[{h+1}] = {array[h+1]} & array[{u}] = {array[u]},'
            #       f'schedule: {array}, with travel distance: {travel_distance_after_swap}')

            if travel_distance_after_swap < travel_distance_wo_swap:
                min = travel_distance_after_swap
        return min

    elif(s == h+1): # h -> s
        if s == len(given_array):
            return Get_Distance(given_array, h, 0)
        else:
            return Get_Distance(given_array, h, s)

    else:
        return 0

def Get_Distance(array, x, y):
    return Target_Data[array[x]][array[y]]

def Get_Schedule_Length(given_schedule):
    sum = 0
    for j in range(len(given_schedule)-1):
        sum += Target_Data[given_schedule[j],given_schedule[j+1]]
    return sum

In [56]:
# schedule = np.arange(len(Target_Data))
schedule = list(range(len(Target_Data)))
print(schedule)

schedule.append(schedule[0])
print(schedule)
print(Get_Schedule_Length(schedule))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0]
161


In [57]:
min = Minimum_Travel_Distance_by_DP(schedule, 0, len(schedule)-1)
print(min)
print(schedule)

153
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0]


In [58]:
A = [1, 2, 3]
print(A[0:3])

X = np.concatenate((A,A))
print(X)

[1, 2, 3]
[1 2 3 1 2 3]


In [59]:
A = "test"
B = A
B = "exam"
print(A)
print(B)
print(A)

test
exam
test


In [60]:
A = 1
B = A
B = 2
print(A)
print(B)

1
2
